---
- name: Create required OVS bridges
  openvswitch_bridge:
    bridge: "{{ item }}"
    state: present
  with_items:
    - br-ext
    - br-vlan

- template:
    src: hostProfile.sh.j2
    dest: /tmp/hostProfile.sh
    mode: 0740

- command: /tmp/hostProfile.sh
