- name: Download Platform9 installer downloader
  command: curl -O https://raw.githubusercontent.com/platform9/support-locker/master/installer/pf9-download.py
  args:
    chdir: /tmp

- name: Download Platform9 installer
  shell: python /tmp/pf9-download.py --account_endpoint pf9-midonet-test.platform9.net --region {{ os_region }} --user {{ os_username }} --password {{ os_password }} --tenant {{ os_tenant }} --platform {{ item }}
  args:
    chdir: /tmp
  with_items:
    - debian
    - redhat
