---
- name: Install ostackhost role
  role_authorize:
    auth_tenant_name: "{{ os_tenant }}"
    auth_user: "{{ os_username }}"
    auth_password: "{{ os_password }}"
    #auth_token: "{{ hostvars['localhost']['os_auth_token'] }}"
    host_ip: "{{ ip_address }}"
    controller_url: "{{ du_url }}"
    role_name: pf9-ostackhost
    state: present
    role_data:
      novncproxy_base_url: "http://{{ vnc_ip }}:6080/vnc_auto.html"

- name: Install midolman role
  role_authorize:
     auth_token: "{{ hostvars['localhost']['os_auth_token'] }}"
     host_ip: "{{ ip_address }}"
     controller_url: "{{ du_url }}"
     role_name: midolman
     state: present
     role_data:
         zookeeper_hosts: "{{ nsdb_hosts }}"
